mon_projet/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('generate_pdf/<int:employee_id>/', views.generate_employee_pdf_indiv, name='generate_employee_pdf'),
    path('manager/', views.manager_dashboard, name='manager_dashboard'),
    path('admin/', views.admin_dashboard, name='admin_dashboard'),
    path('add_account_type/', views.add_account_type, name='add_account_type'),
    path('employee_form/', views.add_account_type, name='employee_form'),
    path('add_profile/', views.add_profile, name='add_profile'),
    path('add_manager/', views.add_manager, name='add_manager'),
    path('add_employee/', views.add_employee, name='add_employee'),
    path('generate_pdf/', views.generate_pdf, name='generate_pdf'),
    path('employee/<int:pk>/edit/', views.edit_employee, name='edit_employee'),
    path('employee/<int:pk>/delete/', views.delete_employee, name='delete_employee'),
    path('edit_manager/<int:manager_id>/', views.edit_manager, name='edit_manager'),
    path('delete_manager/<int:manager_id>/', views.delete_manager, name='delete_manager'),
    path('add_department/', views.add_department, name='add_department'),
    path('generate_pdf/<int:employee_id>/', views.generate_pdf, name='generate_pdf'),
    path('get_account_types/', views.get_account_types, name='get_account_types'),
    path('logout/', views.logout_view, name='logout'),
]

mon_projet/mon_projet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

mon_projet/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class AccountType(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class Profile(models.Model):
    name = models.CharField(max_length=100)
    account_types = models.ManyToManyField(AccountType)

    def __str__(self):
        return self.name

class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
class Department(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name
    
class Employee(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    account_types = models.ManyToManyField(AccountType, through='EmployeeAccountType')
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    hire_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class EmployeeAccountType(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    account_type = models.ForeignKey(AccountType, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.employee} - {self.account_type}"

mon_projet/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import AccountType, Manager, Employee, Profile,Department
from django import forms
from django.contrib.auth.models import User


class AccountTypeForm(forms.ModelForm):
    class Meta:
        model = AccountType
        fields = ['name', 'description']

class ProfileForm(forms.ModelForm):
    account_types = forms.ModelMultipleChoiceField(
        queryset=AccountType.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
        label="Types de comptes"
    )

    class Meta:
        model = Profile
        fields = ['name', 'account_types']
        labels = {
            'name': 'Nom du profil'
        }

class ManagerForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)
    username = forms.CharField(max_length=150, required=True)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

class EmployeeForm(forms.ModelForm):
    profile = forms.ModelChoiceField(queryset=Profile.objects.all(), required=False, label='Profile')
    account_types = forms.ModelMultipleChoiceField(
        queryset=AccountType.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label='Account Types'
    )
    department = forms.ModelChoiceField(queryset=Department.objects.all(), required=False)

    class Meta:
        model = Employee
        fields = ['first_name', 'last_name', 'email', 'department', 'profile','account_types']

    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        if 'account_types' in self.data:
            try:
                self.fields['account_types'].queryset = AccountType.objects.all()
            except (ValueError, TypeError):
                self.fields['account_types'].queryset = AccountType.objects.none()
        elif self.instance.pk:
            self.fields['account_types'].queryset = self.instance.account_types.all()

    def save(self, commit=True):
        instance = super(EmployeeForm, self).save(commit=False)
        if commit:
            instance.save()
            self.save_m2m()
        return instance
    
class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['name']

mon_projet/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.http import HttpResponse, JsonResponse, Http404
from django.template.loader import get_template
from django.conf import settings

from .forms import AccountTypeForm, ManagerForm, EmployeeForm, ProfileForm, DepartmentForm
from .models import AccountType, Manager, Employee, Profile, EmployeeAccountType

from xhtml2pdf import pisa
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

import os
import io
import pandas as pd

from django.views.decorators.csrf import csrf_protect
from django.db.models import Q

@csrf_protect
@login_required
def edit_employee(request, pk):
    try:
        employee = get_object_or_404(Employee, pk=pk)
    except Http404:
        messages.error(request, "This employee does not exist.")
        return redirect('manager_dashboard')  # Redirigez vers une vue appropriée

    if request.method == 'POST':
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            messages.success(request, 'Employee updated successfully.')
            return redirect('manager_dashboard')
    else:
        form = EmployeeForm(instance=employee)
        
    managers = Manager.objects.all()  # Incluez les managers dans le contexte
    return render(request, 'accounts/add_employee.html', {'form': form, 'managers': managers,'action': 'edit'})

@csrf_protect
@login_required
def generate_employee_pdf_indiv(request, employee_id):
    employee = get_object_or_404(Employee, id=employee_id)

    # Préparer les données pour le PDF
    data = {
        'Nom': employee.last_name,
        'Prénom': employee.first_name,
        'Email': employee.email,
        'Département': employee.department.name if employee.department else '',
        'Compte': ', '.join([account.name for account in employee.account_types.all()])
    }

    buffer = io.BytesIO()
    pdf = SimpleDocTemplate(buffer, pagesize=letter)

    # Créer des styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(name='TitleStyle', parent=styles['Title'], fontSize=22, alignment=1)
    normal_style = ParagraphStyle(name='NormalStyle', parent=styles['Normal'], fontSize=14, alignment=0)

    # Créer le titre
    title = Paragraph(f"Rapport de {employee.first_name} {employee.last_name} ({employee_id})", title_style)
    
    # Espacement entre le titre et le contenu
    spacer = Spacer(1, 0.5 * inch)

    # Créer le contenu du PDF
    content = [title, spacer]
    for key, value in data.items():
        content.append(Paragraph(f"<b>{key}:</b> {value}", normal_style))
        content.append(Spacer(1, 0.2 * inch))  # Espacement entre les lignes de contenu

    # Ajuster la largeur de la colonne pour occuper toute la largeur de la page
    pdf.build(content)

    # Récupérer le PDF en mémoire
    buffer.seek(0)
    
    # Nom du fichier basé sur le nom et l'ID de l'employé
    filename = f"{employee.first_name}_{employee.last_name}_{employee_id}.pdf"
    
    response = HttpResponse(buffer, content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    return response


@csrf_protect
@login_required
def manager_dashboard(request):
    query = request.GET.get('q')
    if query:
        employees = Employee.objects.filter(
            Q(first_name__icontains=query) |
            Q(last_name__icontains=query) |
            Q(email__icontains=query) |
            Q(department__name__icontains=query) |
            Q(account_types__name__icontains=query)
        ).distinct()
    else:
        employees = Employee.objects.all()

    # Définir le message à passer au template
    no_results_message = "Aucun utilisateur trouvé" if not employees.exists() else ""
    
    managers = Manager.objects.all()  # Inclure les managers dans le contexte

    return render(request, 'accounts/manager_dashboard.html', {
        'employees': employees,
        'managers': managers,
        'no_results_message': no_results_message  # Passer le message au template
    })
@csrf_protect
@login_required
def generate_pdf(request):
    # Récupérer les données de la base de données
    employees = Employee.objects.prefetch_related('account_types', 'department')

    # Préparer les données pour le DataFrame
    data = []
    for employee in employees:
        account_types = ', '.join([account.name for account in employee.account_types.all()])
        data.append({
            'Nom': employee.last_name,
            'Prenom': employee.first_name,
            'Email': employee.email,
            'Departement': employee.department.name if employee.department else '',
            'Compte': account_types
        })

    df = pd.DataFrame(data)

    # Créer un fichier PDF en mémoire
    buffer = io.BytesIO()
    pdf = SimpleDocTemplate(buffer, pagesize=letter)

    # Créer des styles
    styles = getSampleStyleSheet()
    title_style = styles['Title']
    table_style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ])

    # Créer le titre
    title = Paragraph("Rapport des Employés avec Départements et Comptes", title_style)

    # Créer le tableau
    table = Table([df.columns.tolist()] + df.values.tolist())
    table.setStyle(table_style)

    # Ajouter le titre et le tableau au document PDF
    elements = [title, table]
    pdf.build(elements)

    # Récupérer le PDF en mémoire et le retourner dans la réponse HTTP
    buffer.seek(0)
    return HttpResponse(buffer, content_type='application/pdf')

@csrf_protect
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user.is_superuser:
                return redirect('admin_dashboard')
            elif hasattr(user, 'manager'):
                return redirect('manager_dashboard')
            else:
                return redirect('manager_dashboard')  # Redirecting to manager_dashboard as default
        else:
            return render(request, 'accounts/login.html', {'error': 'Username or password incorect'})
    return render(request, 'accounts/login.html')
# views.py

@csrf_protect
@login_required
def get_account_types(request, profile_id):
    profile = Profile.objects.get(id=profile_id)
    account_types = profile.account_types.values_list('id', flat=True)
    return JsonResponse({'account_types': list(account_types)})

@csrf_protect
@login_required
def is_admin(user):
    return user.is_superuser

@csrf_protect
@login_required
def edit_manager(request, manager_id):
    try:
        manager = get_object_or_404(Manager, id=manager_id)
    except Http404:
        messages.error(request, "This manager does not exist.")
        return redirect('admin_dashboard')  # Redirigez vers une vue appropriée

    if request.method == 'POST':
        form = ManagerForm(request.POST, instance=manager.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Manager updated successfully.')
            return redirect('admin_dashboard')
    else:
        form = ManagerForm(instance=manager.user)
        
    return render(request, 'accounts/edit_manager.html', {'form': form, 'manager': manager})


@csrf_protect
@login_required
def delete_manager(request, manager_id):
    manager = get_object_or_404(Manager, id=manager_id)
    
    # Supprimer le manager directement sans confirmation
    manager.user.delete()
    messages.success(request, 'Manager deleted successfully.')
    
    return redirect('admin_dashboard')

@csrf_protect
@login_required
def delete_employee(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    
    # Supprimer l'employé directement sans confirmation
    employee.delete()
    messages.success(request, 'Employee deleted successfully.')
    
    return redirect('manager_dashboard')

@csrf_protect
@login_required
def logout_view(request):
    logout(request)
    return redirect('login')

@csrf_protect
@login_required
def admin_dashboard(request):
    managers = Manager.objects.all()
    return render(request, 'accounts/admin_dashboard.html', {'managers': managers})

@csrf_protect
@login_required
def add_account_type(request):
    if request.method == 'POST':
        form = AccountTypeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_dashboard')
    else:
        form = AccountTypeForm()
    managers = Manager.objects.all()  # Include managers in the context
    return render(request, 'accounts/add_account_type.html', {'form': form, 'managers': managers})

@csrf_protect
@login_required
def add_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_dashboard')
    else:
        form = ProfileForm()
    account_types = AccountType.objects.all()
    managers = Manager.objects.all()  # Include managers in the context
    return render(request, 'accounts/add_profile.html', {'form': form, 'account_types': account_types, 'managers': managers})

@csrf_protect

mon_projet/accounts/templates/accounts/add_account_type.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Account Type</title>
    <link rel="stylesheet" href="{% static 'css/add_account.css' %}">
</head>
<body>
    <div class="container">
        <h2>Add Account Type</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Name:</label>
                <input type="text" id="id_name" name="name" required>
                {{ form.name.errors }}
            </div>
            <div class="form-group">
                <label for="id_description">Description:</label>
                <textarea id="id_description" name="description" rows="4"></textarea>
                {{ form.description.errors }}
            </div>
            <button type="submit" class="btn">Add</button>
        </form>
    </div>
</body>
</html>

mon_projet/accounts/templates/accounts/add_department.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Department</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <h2>Add Department</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Add Department</button>
        </form>
    </div>
</body>
</html>

mon_projet/accounts/templates/accounts/add_employee.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>
        {% if action == 'edit' %}
            Edit Employee
        {% else %}
            Add Employee
        {% endif %}
    </title>
    <link rel="stylesheet" href="{% static 'css/add_employee.css' %}">
</head>
<body>
    <div class="form-container">
        <h1>
            {% if action == 'edit' %}
                Edit Employee
            {% else %}
                Add Employee
            {% endif %}
        </h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group">
                    {{ form.profile.label_tag }}
                    {{ form.profile }}
                </div>
                <div class="form-group" id="id_account_types">
                    {{ form.account_types.label_tag }}
                    <div class="checkbox-container">
                        {% for checkbox in form.account_types %}
                        <div class="checkbox-item">
                            {{ checkbox.tag }}
                            {{ checkbox.choice_label }}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.first_name.label_tag }}
                {{ form.first_name }}
            </div>
            <div class="form-group">
                {{ form.last_name.label_tag }}
                {{ form.last_name }}
            </div>
            <div class="form-group">
                {{ form.email.label_tag }}
                {{ form.email }}
            </div>
            <div class="form-group">
                {{ form.department.label_tag }}
                {{ form.department }}
            </div>
            {% if form.non_field_errors %}
                <div class="error">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            {% for field in form %}
                {% if field.errors %}
                    <div class="error">
                        {{ field.errors }}
                    </div>
                {% endif %}
            {% endfor %}
            <button type="submit">
                {% if action == 'edit' %}
                     Update Employee
                {% else %}
                     Add Employee
                {% endif %}
        </button>
        </form>
    </div>
    <script src="{% static 'js/profile_selection.js' %}"></script>
</body>
</html>

mon_projet/accounts/templates/accounts/add_manager.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Manager</title>
    <link rel="stylesheet" href="{% static 'css/add_manager.css' %}">
</head>
<body>
    <div class="container">
        <h2>Add Manager</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {{ form.as_p }}
            <button type="submit" class="btn">Add</button>
        </form>
    </div>
</body>
</html>

mon_projet/accounts/templates/accounts/add_profile.html
<!DOCTYPE html>
<html lang="fr">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un profil</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <h2>Ajouter un profil</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Nom du profil:</label>
                <input type="text" id="id_name" name="name" required>
            </div>
            <div class="form-group">
                <label for="id_account_types">Types de comptes:</label>
                {{ form.account_types }}
            </div>
            <button type="submit" class="btn">Ajouter</button>
        </form>
    </div>
</body>
</html>

mon_projet/accounts/templates/accounts/admin_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <h2>Admin Dashboard</h2>
        
        <!-- Action Buttons -->
        <div class="actions">
            <a href="{% url 'add_account_type' %}" class="btn btn-add">Add Account Type</a>
            <a href="{% url 'add_profile' %}" class="btn btn-add">Add Profile</a>
            <a href="{% url 'add_manager' %}" class="btn btn-add">Add Manager</a>
            <a href="{% url 'add_department' %}" class="btn btn-add">Add departement</a>
        </div>
        
        <!-- Manager Table -->
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for manager in managers %}
                <tr>
                    <td>{{ manager.user.first_name }} {{ manager.user.last_name }}</td>
                    <td>{{ manager.user.email }}</td>
                    <td>
                        <!-- Edit Button -->
                        <a href="{% url 'edit_manager' manager.id %}" class="btn btn-edit">Edit</a>
                        
                        <!-- Delete Button -->
                        <form action="{% url 'delete_manager' manager.id %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

mon_projet/accounts/templates/accounts/confirm_delete_employee.html
<!-- confirm_delete_employee.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm Delete</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <h2>Confirm Delete</h2>
        <p>Are you sure you want to delete {{ employee.first_name }} {{ employee.last_name }}?</p>
        <form method="post" action="{% url 'delete_employee' employee.pk %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Confirm</button>
            <a href="{% url 'manager_dashboard' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</body>
</html>

mon_projet/accounts/templates/accounts/confirm_delete_manager.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm Delete</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <h2>Confirm Delete</h2>
        <p>Are you sure you want to delete {{ manager.first_name }} {{ manager.last_name }}?</p>
        <form action="{% url 'delete_manager' manager.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Confirm</button>
            <a href="{% url 'admin_dashboard' %}" class="btn">Cancel</a>
        </form>
    </div>
</body>
</html>

mon_projet/accounts/templates/accounts/edit_manager.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Manager</title>
    <link rel="stylesheet" href="{% static 'css/edit_manager.css' %}">
</head>
<body>
    <div class="container">
        <h2>Edit Manager</h2>
        <form method="post" action="{% url 'edit_manager' manager.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="btn-container">
                <button type="submit" class="btn btn-primary">Save Changes</button>
                <a href="{% url 'admin_dashboard' %}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
</body>
</html>

mon_projet/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <h2>Login</h2>
            {% if error %}
                <div class="error">{{ error }}</div>
            {% endif %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit" class="btn">Login</button>
        </form>
    </div>
</body>
</html>

mon_projet/accounts/templates/accounts/manager_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manager Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
</head>
<body>
    <div class="container">
        <h1>Manager Dashboard</h1>

        <!-- Display success or error messages -->
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <!-- Search form -->
        <form method="get" action="{% url 'manager_dashboard' %}">
            <input type="text" name="q" placeholder="Search employees..." value="{{ request.GET.q }}">
            <button type="submit">Search</button>
        </form>
        
        <!-- Display no results message or the employee table -->
        {% if no_results_message %}
        <p class="messagesrecherche">{{ no_results_message }}</p>
        {% else %}
            <!-- Employees table -->
            <table>
                <thead>
                    <tr>
                        <th>Employee Name</th>
                        <th>Email</th>
                        <th>Account Types</th>
                        <th>Department</th>
                        <th>Hire Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for employee in employees %}
                    <tr>
                        <td>{{ employee.first_name }} {{ employee.last_name }}</td>
                        <td>{{ employee.email }}</td>
                        <td>
                            {% for account_type in employee.account_types.all %}
                                {{ account_type.name }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </td>
                        <td>{{ employee.department }}</td>
                        <td>{{ employee.hire_date }}</td>
                        <td>
                            <div class="btn-container">
                                <div class="btn-group btn-group-top">
                                    <a href="{% url 'edit_employee' employee.id %}" class="btn btn-edit">Editer</a>
                                    <form action="{% url 'delete_employee' employee.id %}" method="post" class="btn-group">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Supprimer</button>
                                    </form>
                                </div>
                                <a href="{% url 'generate_employee_pdf' employee.id %}" class="btn btn-pdf btn-bottom">Télécharger</a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}

        <!-- Add Employee Button -->
        <a href="{% url 'add_employee' %}" class="btn btn-add">Add Employee</a>

        <!-- Download All PDFs Button -->
        <a href="{% url 'generate_pdf' %}" class="btn btn-pdf">Download PDF</a>

        <!-- Logout Link -->
        <a href="{% url 'logout' %}" class="btn btn-logout">Logout</a>
    </div>
</body>
</html>

mon_projet/accounts/templates/accounts/pdf_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee PDF</title>
    
</head>
<body>
    <div class="container">
        <h2>Employee Details</h2>
        {% for employee in employees %}
            <div class="employee-details">
                <p><strong>Name:</strong> {{ employee.first_name }} {{ employee.last_name }}</p>
                <p><strong>Email:</strong> {{ employee.email }}</p>
                <p><strong>Department:</strong> {{ employee.department }}</p>
                <p><strong>Account Types:</strong>
                    {% for account_type in employee.account_types.all %}
                        {{ account_type.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                <hr>
            </div>
        {% endfor %}
    </div>
</body>
</html>